Algoritmo "funções - exercicio4"
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 09/02/2022
Var
// Seção de Declarações das variáveis 

x,z,p:real

funcao potencia:real

inicio

p<-(x^z)

retorne p

fimfuncao

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...

escreval("Introduza o termo x:")
    leia(x)
escreval("Introduza o termo z:")
    leia(z)

p<-potencia

escreval("O número",x," elevado à potência",z," é:",p)


Fimalgoritmo